#!/usr/bin/env python3
import re, subprocess, requests

def sendNotif(msg):
    url = f"https://api.telegram.org/bot%BOT_TOKEN%/sendMessage?chat_id=%CHAT_ID%&text={message}&parse_mode=HTML"
    print(requests.get(url).json())

def getPackages(action:str, stdout:str)->list:
    reg = re.compile(rf'{action}:\n(  .+(?:\n  .+)*)')
    processed = reg.findall(stdout)

    postreg = re.compile(r'(\S+)')
    packages = [] 

    for p in processed:
        packages += postreg.findall(p)

    return packages

def getHostname()->str:
    with open('/etc/hostname', 'r') as f:
        name = f.read().rstrip()
        f.close()

    return name

def setupMessage(data:dict)->str:
    notification = ""

    for message, packages in data.items():
        l = len(packages)
        if l > 0:
            notification += f"\n<b>{str(l)}</b> {message}"
            for i in packages:
                notification += f"\n  - {i}"

    if len(notification) == 0:
        return ""
    else:
        return f"<u>pLUM on {getHostname()} :</u>" + notification

if __name__ == "__main__":

    subprocess.run(["apt-get", "update"], capture_output=True)
    stdout = subprocess.run(["apt-get", "--simulate", "full-upgrade"], capture_output=True).stdout.decode()

    up = getPackages("upgraded", stdout)
    rm = getPackages("no longer required", stdout)

    message = setupMessage({"to upgrade":up, "to remove":rm})

    if message != "":
        sendNotif(message)
