#!/usr/bin/env python3
import re, subprocess, requests

def sendNotif(msg):
    url = f"https://api.telegram.org/bot%BOT_TOKEN%/sendMessage?chat_id=%CHAT_ID%&text={message}&parse_mode=HTML"
    print(requests.get(url).json())

def getUpgardes():
    subprocess.run(["apt-get", "update"], capture_output=True)
    upgrade = subprocess.run(["apt-get", "--simulate", "full-upgrade"], capture_output=True).stdout.decode()
    reg = re.compile(r'\n\s{2}(.+)')
    
    packages = []
    for r in reg.findall(upgrade):
        packages += r.split(' ')

    return packages

def getHostname():
    with open('/etc/hostname', 'r') as f:
        name = f.read().rstrip()
        f.close()

    return name

if __name__ == "__main__":

    up = getUpgardes()
    if len(up) > 0:
        if len(up) == 1:    
            message = f"<b>pLUM on <u>{getHostname()}</u> - 1 update available:</b>"
        else:
            message = f"<b>pLUM on <u>{getHostname()}</u> - {len(up)} updates available:</b>"

        for i in up:
            message += f"\n - {i}"

        sendNotif(message)

